config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users, controllers: {
    sessions: 'end_users/sessions',
    passwords: 'end_users/passwords',
    registrations: 'end_users/registrations'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'end_users/orders/confirm' => 'end_users/orders#confirm', as: 'end_users_confirm_order'
  get 'end_users/orders/finish' => 'end_users/orders#finish', as: 'end_users_finish_order'

  get 'admins' => 'admins#top', as: 'top_admin'
  delete '/end_users/cart_items' => 'end_users/cart_items#destroy_all', as:'destroy_all'

  resource :end_user, only: [:edit, :show, :update] do
    patch :delete
    get :leave
  end

  namespace :end_users do
    resources :products, only: [:index, :show]
    resources :genres, only: [:show]
    resources :cart_items, only: [:index, :show, :update, :destroy, :create]
    resources :ship_addresses, only: [:index, :edit, :update, :destroy, :create]
    resources :orders, only: [:index, :new, :show, :create]
  end


  namespace :admins do
  resources :end_users, only: [:index, :edit, :show, :update]
  resources :orders, only: [:index, :show, :update]
  resources :genres, only: [:index, :edit, :create, :update]
  resources :products, only: [:index, :new, :edit, :show, :create, :update, :destroy]
  end

  root 'end_users/products#top'
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products
  accepts_nested_attributes_for :order_products

  belongs_to :end_user

  enum payment: { クレジットカード: 0, 銀行振込: 1 }
  enum status: { 入金待ち: 0, 入金確認: 1,
                製作中: 2, 発送準備中: 3, 発送済み: 4 }
  enum production_status: { 着手不可: 0, 製作待ち: 1,
                製作中: 2, 製作完了: 3}, _prefix: true

  def sum
    sum = 0
    order_products.each do |item|
      sum += (item.tax_included_price * item.quantity)
    end
    sum
  end

  validates :address_name, :address, presence: true
  validates :post_code, format: { with: /\A\d{7}\z/ }
end

app/controllers/admins/orders_controller.rb
  class Admins::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders  = Order.all.order(created_at: :asc)
    @orders  = Order.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
    @order_product = OrderProduct.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order_products = @order.order_products
    @order.update(order_params)
    @order_products.each do |order_product|
    if order_product.production_status == "製作中"
      @order.status = "製作中"
    end
    end

    if @order_products.all? do |order_product|
      order_product.production_status == "製作完了"
      end
      @order.status = "発送準備中"
    end

    if @order.status == "入金確認"
      relation_status
    end
      @order.update(order_params)
      redirect_to admins_order_path(@order)
  end

  private

    # 注文ステータスと製作ステータスを関連づけて、自動化する
    def relation_status
      @order.order_products.each do |item|
        item.production_status = "製作待ち"
        item.save
      end
    end

    def order_params
      params.require(:order).permit(:status, order_products_attributes: [:production_status, :_destroy, :id])
    end
end

app/controllers/end_users/orders_controller.rb
class EndUsers::OrdersController < ApplicationController
  before_action :authenticate_end_user!
  before_action :set_current_end_user

  def new
    if @end_user.cart_items.empty?
      redirect_to end_users_cart_items_path
    else
      @ship_addresses = @end_user.ship_addresses
      @order = Order.new
    end
  end

  def confirm
    @order = Order.new(order_params)
    @cart_items = @end_user.cart_items
    case params[:add]
    when "1"
      @order.post_code = @end_user.post_code
      @order.address = @end_user.address
      @order.address_name = @end_user.last_name + @end_user.first_name
    when "2"
      @ship_address = ShipAddress.find(params[:order][:end_user_id])
      @order.post_code = @ship_address.post_code
      @order.address = @ship_address.address
      @order.address_name = @ship_address.address_name
    when "3"
      @ship_address = ShipAddress.new(
        end_user_id: @end_user.id,
        post_code: @order.post_code,
        address: @order.address,
        address_name: @order.address_name)
      @ship_address.save
    end
  end

  def create
    @cart_items = @end_user.cart_items
    @order = Order.new(order_params)
    @order.end_user_id = @end_user.id
    if @order.save
      @cart_items.each do |item|
        @order_product = OrderProduct.new(
          product_id: item.product.id,
          order_id: @order.id,
          quantity: item.quantity,
          tax_included_price: (item.product.tax_excluded_price * 1.1))
        @order_product.save
        item.destroy
      end
      redirect_to end_users_finish_order_path(@order)
    else
      flash.now[:danger] = "入力情報に間違いがあります"
      render :new
    end
  end

  def index
    @orders = @end_user.orders
  end

  def show
    @order = Order.find(params[:id])
    unless @order.end_user == @end_user
      redirect_to end_users_orders_path
    end
    @order_products = @order.order_products
  end


  def finish
  end

  private
    def order_params
      params.require(:order).permit(:id, :end_user_id, :post_code, :address_name, :address, :total, :payment, :status)
    end
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/end_users/orders_helper.rb
module EndUsers::OrdersHelper
end

app/views/admins/orders/index.html.erb
<div class="row">
    <div class="orders-title">
      <h1>注文一覧画面</h1>
    </div>
    <div class="orders-box">
      <%= paginate @orders %>

      <table class='table'>

        <thead>
          <tr class="active">
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td>
              <%= link_to admins_order_path(order) do %>
              <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
              <% end %>
            </td>

            <td>
              <%= order.address_name %>
            </td>
            <td>
              <% total_quantity = 0 %>
              <% order.order_products.each { |item| total_quantity += item.quantity } %>
              <%= total_quantity %>
            </td>

            <td>
              <%= order.status %>
            </td>

          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @orders %>
    </div>
</div>

app/views/admins/orders/show.html.erb
<div class="row">
  <div class="order-title">
    <h1>注文詳細画面</h1>
  </div>

  <div class="col-xs-9">
    <div class="customer-box">
      <%= form_for [:admins, @order] do |f| %>
      <label for="name"> 購入者 </label>
      <%= link_to admins_end_user_path(@order.end_user) do %>
      <%= @order.end_user.last_name %><%= @order.end_user.first_name %>
      <% end %><br>

      <label for="ship_addresses"> 配送先 </label>
      〒 <%= @order.post_code %>
      <%= @order.address %>
      <%= @order.address_name %><br>

      <label for="payment"> 支払方法 </label>
      <%= @order.payment %> <br>
      <div class="order_status">
        <%= f.label :注文ステータス %>
        <%= f.select :status, Order.statuses.keys %>
      </div>
      <div class="order_status_actions">
        <%= f.submit "更新", class: 'btn-xs btn-primary' %>
      </div>
      <% end %>

    </div>

    <div class="order-box">
      <table class='table'>

        <thead>
          <tr class="active">
            <th>商品名</th>
            <th>単価 (税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>

        <tbody>
          <%= form_for [:admins, @order] do |f| %>
          <%= f.fields_for :order_products do |item| %>
          <tr>
            <td><%= item.object.product.name %></td>
            <td><%= item.object.tax_included_price.to_s(:delimited) %></td>
            <td><%= item.object.quantity %></td>
            <td><%= (item.object.tax_included_price * item.object.quantity).to_s(:delimited) %></td>
            <td>

              <div class="production_status">
                <%= item.select :production_status, Order.production_statuses.keys %>
              </div>
              <div class="production_status_actions">
                <%= f.submit "更新", class: 'btn-xs btn-primary' %>
              </div>
            </td>
          </tr>
          <% end %>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>

  <div class="col-xs-3">
    <div class="price-box">
      <label for="total"> 商品合計 </label>
      <%= @order.total.to_s(:delimited) %> 円 <br>
      <label for="postage"> 送料 </label>
      <%= @order.postage %> 円 <br>
      <label for=""> 請求金額合計 </label>
      <%= (@order.total + @order.postage).to_s(:delimited) %> 円 <br>
    </div>
  </div>
</div>