config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users, controllers: {
    sessions: 'end_users/sessions',
    passwords: 'end_users/passwords',
    registrations: 'end_users/registrations'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'end_users/orders/confirm' => 'end_users/orders#confirm', as: 'end_users_confirm_order'
  get 'end_users/orders/finish' => 'end_users/orders#finish', as: 'end_users_finish_order'

  get 'admins' => 'admins#top', as: 'top_admin'
  delete '/end_users/cart_items' => 'end_users/cart_items#destroy_all', as:'destroy_all'

  resource :end_user, only: [:edit, :show, :update] do
    patch :delete
    get :leave
  end

  namespace :end_users do
    resources :products, only: [:index, :show]
    resources :genres, only: [:show]
    resources :cart_items, only: [:index, :show, :update, :destroy, :create]
    resources :ship_addresses, only: [:index, :edit, :update, :destroy, :create]
    resources :orders, only: [:index, :new, :show, :create]
  end


  namespace :admins do
  resources :end_users, only: [:index, :edit, :show, :update]
  resources :orders, only: [:index, :show, :update]
  resources :genres, only: [:index, :edit, :create, :update]
  resources :products, only: [:index, :new, :edit, :show, :create, :update, :destroy]
  end

  root 'end_users/products#top'
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :product
	belongs_to :end_user
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :ship_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  enum is_deleted: { 有効: false, 退会済み: true }

  validates :last_name, :first_name, :address, presence: true
  validates :last_name_kana, :first_name_kana,
    format: {with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力してください。'}
  validates :post_code, format: { with: /\A\d{7}\z/ }
  validates :phone_number, format: { with: /\A\d{10,11}\z/ }
end

app/controllers/admins/end_users_controller.rb
class Admins::EndUsersController < ApplicationController
   before_action :authenticate_admin!

   def index
      @end_users = EndUser.all.order(created_at: :asc)
      @end_users = EndUser.page(params[:page]).per(10)
   end

   def show
      @end_user = EndUser.find(params[:id])
   end

   def edit
      @end_user = EndUser.find(params[:id])
   end

   def update
      @end_user = EndUser.find(params[:id])
      if @end_user.update(end_user_params)
         redirect_to admins_end_user_path(@end_user.id)
      else
         render :edit
      end
   end

   private
      def end_user_params
         params.require(:end_user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number, :email, :is_deleted)
      end
end

app/controllers/end_users/cart_items_controller.rb
class EndUsers::CartItemsController < ApplicationController
	before_action :authenticate_end_user!

	def index
			@end_user  = current_end_user
			@cart_items = @end_user.cart_items
			@cart_item = CartItem.new
	end

	def show
			@end_user  = current_end_user
			@cart_items = @end_user.cart_items
			@cart_item = CartItem.new
	end

	def update
			@cart_item = CartItem.find(params[:id])
			@cart_item.update(cart_item_params)
			redirect_to end_users_cart_items_path
	end

	def destroy
			@cart_item = CartItem.find(params[:id])
			@cart_item.destroy
			@cart_item_id = @cart_item.id
			@end_user  = current_end_user
			@cart_items = @end_user.cart_items
			flash[:success] = "商品を削除しました"
			redirect_to end_users_cart_items_path
	end

	def destroy_all
		@end_user  = current_end_user
		@cart_items = @end_user.cart_items
		@cart_items.destroy_all
		flash[:success] = "カートを空にしました"
		redirect_to end_users_cart_items_path
	end

	def create
		@cart_item = CartItem.new(cart_item_params)
		@cart_item.end_user_id = current_end_user.id
		if @cart_item.product.is_stopped == "売切れ"
			flash[:danger] = "申し訳ありません。その商品は売切れです"
			redirect_back(fallback_location: root_path)
		else
			redirect_to end_users_cart_items_path
			@cart_item.save
			flash[:success] = "カートに追加しました"
		end
	end

	private
	def cart_item_params
		params.require(:cart_item).permit(:quantity,:product_id,:end_user_id)
	end
end

app/controllers/end_users/confirmations_controller.rb
# frozen_string_literal: true

class EndUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/end_users/genres_controller.rb
class EndUsers::GenresController < ApplicationController
  def show
  	@genre = Genre.find(params[:id])
  	if @genre.is_disabled == "無効"
  		redirect_to root_path
  	end
		@products = @genre.products.page(params[:page]).reverse_order
		@products2 = @genre.products.all
  	@genres = Genre.all
  end

  private
end

app/controllers/end_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class EndUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/end_users/orders_controller.rb
class EndUsers::OrdersController < ApplicationController
  before_action :authenticate_end_user!
  before_action :set_current_end_user

  def new
    if @end_user.cart_items.empty?
      redirect_to end_users_cart_items_path
    else
      @ship_addresses = @end_user.ship_addresses
      @order = Order.new
    end
  end

  def confirm
    @order = Order.new(order_params)
    @cart_items = @end_user.cart_items
    case params[:add]
    when "1"
      @order.post_code = @end_user.post_code
      @order.address = @end_user.address
      @order.address_name = @end_user.last_name + @end_user.first_name
    when "2"
      @ship_address = ShipAddress.find(params[:order][:end_user_id])
      @order.post_code = @ship_address.post_code
      @order.address = @ship_address.address
      @order.address_name = @ship_address.address_name
    when "3"
      @ship_address = ShipAddress.new(
        end_user_id: @end_user.id,
        post_code: @order.post_code,
        address: @order.address,
        address_name: @order.address_name)
      @ship_address.save
    end
  end

  def create
    @cart_items = @end_user.cart_items
    @order = Order.new(order_params)
    @order.end_user_id = @end_user.id
    if @order.save
      @cart_items.each do |item|
        @order_product = OrderProduct.new(
          product_id: item.product.id,
          order_id: @order.id,
          quantity: item.quantity,
          tax_included_price: (item.product.tax_excluded_price * 1.1))
        @order_product.save
        item.destroy
      end
      redirect_to end_users_finish_order_path(@order)
    else
      flash.now[:danger] = "入力情報に間違いがあります"
      render :new
    end
  end

  def index
    @orders = @end_user.orders
  end

  def show
    @order = Order.find(params[:id])
    unless @order.end_user == @end_user
      redirect_to end_users_orders_path
    end
    @order_products = @order.order_products
  end


  def finish
  end

  private
    def order_params
      params.require(:order).permit(:id, :end_user_id, :post_code, :address_name, :address, :total, :payment, :status)
    end
end

app/controllers/end_users/passwords_controller.rb
# frozen_string_literal: true

class EndUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/end_users/products_controller.rb
class EndUsers::ProductsController < ApplicationController
	def top
		@genres = Genre.all
		@products = Product.joins(:genre).where(["genres.is_disabled = ?", 0]).page(params[:page]).reverse_order.per(8)
		@products = @products.all.limit(4)
	end

	def index
		# ↓一覧件数が全件取得できない
		@genres = Genre.all
		@products = Product.joins(:genre).where(["genres.is_disabled = ?", 0]).page(params[:page]).reverse_order.per(8)
		@products_count = Product.joins(:genre).where(["genres.is_disabled = ?", 0]).count
	end

	def show
		@cart_item = CartItem.new
		@product = Product.find(params[:id])
		@genres = Genre.all
	end

	private
	def product_params
		params.require(:product).permit(:name,:introduction,:image,:tax_excluded_price)
	end

end

app/controllers/end_users/registrations_controller.rb
# frozen_string_literal: true

class EndUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users/sessions_controller.rb
# frozen_string_literal: true

class EndUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/end_users/ship_addresses_controller.rb
class EndUsers::ShipAddressesController < ApplicationController
  before_action :set_current_end_user

  def index
    @ship_address = ShipAddress.new
    @ship_addresses = @end_user.ship_addresses
  end

  def create
    @ship_address = ShipAddress.new(ship_address_params)
    @ship_address.end_user_id = @end_user.id
    if @ship_address.save
      flash[:success] = "配送先を登録しました"
      redirect_to end_users_ship_addresses_path
    else
      @ship_addresses = @end_user.ship_addresses
      render :index
    end
  end

  def edit
    @ship_address = ShipAddress.find(params[:id])
  end

  def update
    @ship_address = ShipAddress.find(params[:id])
    if @ship_address.update(ship_address_params)
      flash[:success] = "配送先を更新しました"
      redirect_to end_users_ship_addresses_path
    else
      render :edit
    end
  end

  def destroy
    @ship_address = ShipAddress.find(params[:id])
    @ship_address.destroy
    flash[:success] = "配送先を削除しました"
    redirect_to end_users_ship_addresses_path
  end

  private
    def ship_address_params
      params.require(:ship_address).permit(:address, :post_code, :address_name)
    end
end

app/controllers/end_users/unlocks_controller.rb
# frozen_string_literal: true

class EndUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
  before_action :authenticate_end_user!
  before_action :set_current_end_user
  def show
  end

  def edit
  end

  def update
    if @end_user.update(end_user_params)
      flash[:success] = "会員情報の更新ができました"
      redirect_to end_user_path(@end_user)
    else
      render :edit
    end
  end

  def leave
  end

  def delete
    @end_user.update(is_deleted: true)
    sign_out current_end_user
    flash[:success] = "ありがとうございました。またのご利用を心よりお待ちしております"
    redirect_to root_path
  end

  private
    def end_user_params
      params.require(:end_user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana,
              :email, :post_code, :address, :phone_number, :is_deleted)
    end
end

app/helpers/admins/end_users_helper.rb
module Admins::EndUsersHelper
end

app/helpers/end_users/cart_items_helper 3.rb
module EndUsers::CartItemsHelper
end

app/helpers/end_users/cart_items_helper.rb
module EndUsers::CartItemsHelper
end

app/helpers/end_users/genres_helper.rb
module EndUsers::GenresHelper
end

app/helpers/end_users/order_products_helper.rb
module EndUsers::OrderProductsHelper
end

app/views/end_users/cart_items/index.html.erb
<div class="row">
	<div class ="col-xs-10 col-xs-offset-1">
		<%if @end_user.cart_items.size.zero?%>
			<div>
				<h1>ショッピングカート</h1>
				<div class="" style=" height: 300px; text-align: center;">
					<div style=" height:130px;"></div>
					<strong style = "font-size: 150%; ">カートに商品がありません</strong>
				</div>
			<%=link_to "買い物を続ける","/",class: "btn btn-primary font col-xs-4 col-xs-offset-4"%>
		</div>
		<% else %>
		<h1>ショッピングカート</h1>
			<%=link_to "カートを空にする",destroy_all_path,class: "btn btn-danger col-xs-3 col-xs-offset-9", method: :delete %>
		<div class="col-xs-10" style="height: 50px;">
		</div>

		<table class="table table-bordered">
			<thead>
				<tr class="active">
					<th class="col-xs-4" style="text-align: center;">商品名</th>
					<th style="text-align: center;">単価（税込）</th>
					<th style="text-align: center;">数量</th>
					<th>小計</th>
					<th></th>
				</tr>
			</thead>
		<% @sum = 0 %>
	<%@cart_items.each do |item|%>
		<tbody>
			<tr>
				<td><%= attachment_image_tag(item.product, :image,:fill, 100,100, fallback:"no_image.png", style: "width:45px;height: 40px;")%>
				<%=item.product.name%></td>
				<td style="text-align: center;">¥<%= (item.product.tax_excluded_price * 1.10).floor.to_s(:delimited)%></td>
				<%=form_for [:end_users, item] do |f|%>
					<td>
						<div style="margin-left:auto;"><%= f.select :quantity,[
						['1',1],['2',2],['3',3],['4',4],['5',5],['6',6],['7',7],['8',8],['9',9],['10',10]]%>個　<%=f.submit"変更",class: "btn btn-primary"%></div>
					</td>
				<%end%>
				<td>¥<%= ((item.product.tax_excluded_price)*(item.quantity)* (1.10)).floor.to_s(:delimited)%></td>
				<%@sum += ((item.product.tax_excluded_price)*(item.quantity)* (1.10)).floor%>
				<td ><%= link_to "削除", "/end_users/cart_items/#{item.id}",class: "btn btn-danger", method: :delete%></td>
				</div>
				<%end%>
			</tr>
		</tbody>
	</table>
	<div style="width:30%; margin-left: auto;">
			<table class="table table-bordered" style="margin-left:auto;">
				<thead>
					<tr >
					</tr>
				</thead>
				<tbody>
					<tr>
						<td class="active" style="width: 50%; text-align: center;"><strong>合計金額</strong></td><td style="text-align: center; font-size: 120%;"><%= @sum.to_s(:delimited)%></td>
					</tr>
				</tbody>
			</table>
		</div>
		<div >
			<%=link_to "買い物を続ける","/",class: "btn btn-primary font col-xs-3"%>
		</div>
		<div >
			<%= link_to "情報入力に進む","/end_users/orders/new", class: "btn btn-success font col-xs-3 col-xs-offset-2" %>
		</div>
		</div>
		<% end %>
	</div>
</div>

app/views/end_users/cart_items/show.html.erb
	<div class="row">
		<div class ="col-xs-10 col-xs-offset-1">
		<h1>ショッピングカート</h1>
		<p class= "btn btn-danger col-xs-2 col-xs-offset-10">
			<%=link_to "カートを空にする",destroy_all_path,class: "btn btn-danger", method: :delete %>
		</p>
	<% @sum = 0 %>
	<table class="table table-bordered">
		<thead >
			<tr class="active">
				<th>商品名</th>
				<th>単価（税込）</th>
				<th>数量</th>
				<th>小計</th>
				<th></th>
			</tr>
		</thead>
		<%	@cart_items.each do |item|%>
		<tbody>
			<tr>
				<td><%= attachment_image_tag(item.product, :image,:fill, 100,100, fallback:"no_image.png", size:'100x50')%>
				<%=item.product.name%></td>
				<td>¥<%= (item.product.tax_excluded_price * 1.10).floor%></td>


				<%=form_for model: @cart_item, url: end_users_cart_item_path do |f|%>
				<td><%= f.select :quantity,[[item.quantity.to_i],['1',1],['2',2],['3',3],['4',4],['5',5],['6',6],['7',7],['8',8],['9',9],['10',10]]%>個　<%=f.submit"変更"%></td>
				<%end%>

				<td>¥<%= ((item.product.tax_excluded_price)*(item.quantity)* (1.10)).floor%></td>
				<%@sum += ((item.product.tax_excluded_price)*(item.quantity)* (1.10)).floor%>
				<td><%= link_to "削除", "/end_users/cart_items/#{item.id}",class: "btn btn-danger", method: :delete%></td>
				<%end%>
			</tr>
		</tbody>
	</table>
		<div class="col-xs-3 col-xs-offset-9">
		<table class="table table-bordered">
			<thead>
				<tr >
					<th class="active">合計金額</th>　<th><%= @sum%></th>
				</tr>
			</thead>
		</table>
		</div>
		<div class ="btn btn-success col-xs-3 col-xs-offset-4">
			<%= link_to "情報入力に進む","/end_users/orders/new", class: "font" %>
		</div>
	</div>
</div>